name: encrypt_card
description: An Adyen Flutter plugin to support the Adyen API integration inspired in adyen_flutter https://github.com/lab-box/adyen_flutter.
version: 0.0.2
author: RubenSolAlva
homepage: https://github.com/RubenSolAlva/encrypt_card

environment:
  sdk: ">=2.1.0 <3.0.0"
  flutter: ">=1.10.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.solalva.encrypt.encrypt
        pluginClass: EncryptPlugin
      ios:
        pluginClass: EncryptPlugin